Formula/hab.rb
Can verify with:
```sh
brew untap habitat-sh/habitat
brew tap christophermaier/habitat
brew upgrade hab
hab --version # -> 0.50.3/20171201233208
```
=> Update for hab 0.50.3

Formula/hab.rb
=> Bump to 0.53.0

Formula/hab.rb
=> Bump to version 0.54.0

Formula/hab.rb
Signed-off-by: mwrock <matt@mattwrock.com>
=> bumping brew to to 0.55

Formula/hab.rb
=> Update for the 0.56.0 release

Formula/hab.rb
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>
=> updates formula for 0.57.0

Formula/hab.rb
=> Update to 0.58.0

Formula/hab.rb
Signed-off-by: Josh Black <raskchanky@gmail.com>
=> Update to 0.61.0

Formula/hab.rb
Signed-off-by: Christian Nunciato <chris@nunciato.org>
=> Upgrade to Hab 0.62.0

Formula/hab.rb
=> Release 0.62.1

Formula/hab.rb
=> Update to version 0.63.0

Formula/hab.rb
=> Bump for 0.64.0 release

Formula/hab.rb
=> Bump for 0.64.1 release

Formula/hab.rb
Signed-off-by: mwrock <matt@mattwrock.com>
=> Bump for 0.65.0 release

Formula/hab.rb
=> Bump to 0.66.0

Formula/hab.rb
=> Bump to 0.67.0

Formula/hab.rb
This reverts commit 7b5986d2fef38ee5e00b8e6644df41078e572a60.
=> Revert "Bump version to 0.80.0"

Formula/hab.rb
=> Bump version to 0.85.0

Formula/hab.rb
=> Bump to 0.88.0

Formula/hab.rb
Signed-off-by: Scott Macfarlane <smacfarlane@chef.io>
=> Use current_version, not version

.expeditor/config.yml, .expeditor/verify.pipeline.yml
=> [CI] Create verify pipeline

.expeditor/scripts/verify/install_from_tap.sh, .expeditor/verify.pipeline.yml
=> [CI] Add real verify pipeline actions

.expeditor/scripts/verify/install_from_tap.sh
=> [CI] Don't cleanup so much

.expeditor/verify.pipeline.yml, Formula/hab.rb
Signed-off-by: Matt Wrock <matt@mattwrock.com>
=> Bump version to 1.6.477

.expeditor/scripts/bump_version.sh
Signed-off-by: Matt Wrock <matt@mattwrock.com>
=> use https when querying packages.chef.io

Formula/hab.rb
Signed-off-by: Matt Wrock <matt@mattwrock.com>
=> Bump version to 1.6.568

Formula/hab.rb
Signed-off-by: Matt Wrock <matt@mattwrock.com>
=> Bump version to 1.6.607

Formula/hab.rb
Reverts habitat-sh/homebrew-habitat#72
=> Revert "Bump version to 1.6.1215"
